### ISSUE TITLE
Compiler path is impossible to change

### ISSUE THREAD

**Issue by malfunctioning-object** [franneck94/Vscode-C-Cpp-Runner#21] opened 2021-08-27 23:19 UTC
I can't change compiler/make paths at all - c_cpp_properties.json or C/C++ Runner's settings.json are affected.

Doesn't matter which file I edit, it gets forcefully overwritten. For some weird reason Runner detected g++ and make inside '/usr/bin/core_perl/' path. After removing the 'core_perl' from the path, the save will work for a split second and then refresh back again to the old version with 'core_perl'.

`$ ls -a /usr/bin/core_perl/`
`.   corelist  enc2xs    h2ph  instmodsh  libnetcfg  perldoc  perlthanks  pl2pm     pod2man   pod2usage   prove  ptardiff  shasum  streamzip  zipdetails
..  cpan      encguess  h2xs  json_pp    perlbug    perlivp  piconv      pod2html  pod2text  podchecker  ptar   ptargrep  splain  xsubpp`

g++ and make are present:

`$ g++ --version`
`g++ (GCC) 11.1.0`

`$ which g++`
`/usr/bin/g++`

`$ make --version`
`GNU Make 4.3`
 
`$ which make`
`/usr/bin/make`

What may help investigation is that out of those 3, editing gcc works.

**Comment by franneck94** [comment] 2021-08-28 07:23
Hi,

> For some weird reason Runner detected g++ and make inside '/usr/bin/core_perl/' path. 

This will be fixed by today. I will edir the search rules to only look into /bin/ and /usr/bin/.

> After removing the 'core_perl' from the path, the save will work for a split second and then refresh back again to the old version with 'core_perl'.

I will try to re-simulate this behaviour on my machine.

**Comment by franneck94** [comment] 2021-08-28 08:56
First point is fixed.
I cannot re-simulate the bahviour of the settings/properties files.

**Comment by malfunctioning-object** [comment] 2021-08-28 16:55
Nice!
I have two news, one good and one bad.
I moved to the point where make is being generated, but... I can't really figure out how to define default compiler. For some reason it defaults to gcc in c_cpp_properties.json, and I can't really change it as it is being overwritten. I am not seeing anything appropriate in settings.json or VSCode's settings that would help me update that setting to the appropriate version either.

I am on the fence when it comes to those automatic forced syncs. I feel like it should update only options it provides (modes, paths, linkerArgs, compilerArgs, standards, etc.). I don't understand why it doesn't allow me to change configuration like path it outputs to, name of the output, default compiler option, name of the configuration. Or if it does allow it, then it doesn't communicate well from where it is being pulled.

**Comment by franneck94** [comment] 2021-08-28 17:50
But you tried to set the compiler in the local .vscode/settings.json file, right?

**Comment by malfunctioning-object** [comment] 2021-08-28 19:03
In workspace I am not seeing such option - https://gist.github.com/malfunctioning-object/c19b19857c3511702e8b8c8f4d0df75a
In user's .vscode I am not seeing settings.json.

**Comment by franneck94** [comment] 2021-08-28 21:10
"C_Cpp_Runner.cppCompilerPath"
As in your gist file

**Comment by malfunctioning-object** [comment] 2021-08-28 22:28
That part in settings stays, but during the build a C compiler path is used. I think it's related to 'c_cpp_properties.json' which I can't edit from gcc to g++.
`/usr/bin/gcc -g3 -O0 -g /home/kp/Git/VulkanTest/src/**.cpp -o /home/kp/Git/Test/build/debug/Test  -lglfw -lvulkan -ldl -lpthread -lX11 -lXxf86vm -lXrandr -lXi -o build/Debug/outDebug`
Don't get me wrong, issues following that command can be fixed by adding additional -l flags. But... That is not what is wrong in the first place. Runner should respect cpp source and pull needed libraries simply by using g++ in the first place. I have no idea why gcc was used over g++ for .cpp source but it did.
Another issue is that I specified different output file, in different path, it still looks for 'build/Debug/outDebug'. 
I didn't yet try -O2 flag but at this point I am worried to do so :P

**Comment by malfunctioning-object** [comment] 2021-08-28 22:34
I think we are circling back to the force update issue. Either you give more options to justify force updates or loan some trust to the developer and allow him to adjust script to his needs.

**Comment by franneck94** [comment] 2021-08-29 14:51
> Another issue is that I specified different output file, in different path, it still looks for 'build/Debug/outDebug'.

This is not implemented by this extension. How did you try to define a different output file?

**Comment by franneck94** [comment] 2021-08-29 14:54
> I have no idea why gcc was used over g++ for .cpp source but it did.

This is indded a bug. I will try to reproduce this on my system.
As far as i tested it uses g++ and not gcc for cc/cxx/cpp files.

**Comment by malfunctioning-object** [comment] 2021-08-29 16:53
> > Another issue is that I specified different output file, in different path, it still looks for 'build/Debug/outDebug'.
> 
> This is not implemented by this extension. How did you try to define a different output file?

As seen in gist file, with my own -o flag. Later I posted make command that was generated, it has two -o flags, my own and yours.

**Comment by franneck94** [comment] 2021-08-29 17:18
> > > Another issue is that I specified different output file, in different path, it still looks for 'build/Debug/outDebug'.
> > 
> > 
> > This is not implemented by this extension. How did you try to define a different output file?
> 
> As seen in gist file, with my own -o flag. Later I posted make command that was generated, it has two -o flags, my own and yours.

Okay this is not the intended conent for this setting.

You should pass the files to be compiled as an arg.
This is done by selecting the active folder.
Also you do not have to pass the -g Flag since this would be the Debug mode of this extension.

I guess what you have tried with my extension is just to execute 

```
g++ -g ${workspaceFolder}/src/**.cpp -o ${workspaceFolder}/build/debug/Test
```

What should be done is:

- Setting the active folder to ${workspaceFolder}/src
- Setting the mode to Debug (okay this is the default anyway)
- Click the build button (Gear Button)

**Closed** 2021-09-09 05:52 UTC
Labels: bug

**Comment by Asquator** [comment] 2022-12-13 16:34
I still get the issue. All the three files c_cpp_properties.json, launch.json, settings.json are overridden automatically. I can't change the parameters neither in workspace settings nor in the files. I didn't even know about the existence of _**code_perl**_  directory, and it doesn't contain anything related to gcc. Why can't I change the compiler path?

**Comment by franneck94** [comment] 2022-12-13 18:22
Linux or Mac?

Where is your gcc installed?

So you edit the local .vscode/settings.json file?

**Comment by Asquator** [comment] 2022-12-13 21:37
Linux Manjaro
gcc installed in /usr/bin
I tried to edit .vscode/settings.json directly and via the settings. In any case it's defaulted to /usr/bin/code_perl almost immediately

**Comment by Asquator** [comment] 2022-12-15 18:44
No, I used the default FOSS vscode (code package) on Manjaro at first.
In VsCodium I faced almost no troubles, though.
Some more observation: in both of them, even if the compiler path is detected correctly, the debugger type is overwritten anyways. I want to use type "gdb" or "lldb", but it's defaulted to "cppdbg" and there's no extension of this type available. Is it fixable?

**Comment by franneck94** [comment] 2022-12-15 19:47
cppdbg is Mircosofts C++ extension

**Comment by franneck94** [comment] 2022-12-15 20:09
Can you maybe record a GIF or a Vid to show your use-case

**Comment by franneck94** [comment] 2022-12-21 20:17
Each time I restart the IDE, it gets changed back to "cppdbg". Isn't it related to the Runner extension?
> Yes it is. Might change this.

it's strange that I can't set my own path
> This should be possible, iff the path you enter is valid

**Comment by Asquator** [comment] 2022-12-21 20:34
> Yes it is. Might change this.
It would be really helpful to add a special setting that changes the default debugger type (to change from gdb to lldb for example) , as anybody who uses FOSS probably won't install Microsoft extensions. Otherwise, on every restart/changing working folder, a user has to insert the type manually. It took me some time to even understand what to do. 

> This should be possible, iff the path you enter is valid
Ok. Maybe the Manjaro version is buggy/outdated for some reason.

**Comment by franneck94** [comment] 2022-12-21 21:00
It would be really helpful to add a special setting that changes the default debugger type

> I think there is no way to tell in my code if the user has VSCode or VSCodium opened. Maybe i find a workaround

**Comment by Asquator** [comment] 2022-12-22 08:11
> I think there is no way to tell in my code if the user has VSCode or VSCodium opened. Maybe i find a workaround
I don't think there's a difference. The files get changed in the default VsCode as well, so the issue is not specific to VsCodium.

**Comment by Asquator** [comment] 2023-01-01 14:26
So, do you plan to add the option to change default debugger path?
